# Generated by Django 5.0.3 on 2024-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bma_creator',
            field=models.BooleanField(default=False, help_text='User can upload files to BMA'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bma_curator',
            field=models.BooleanField(default=False, help_text='User can create albums and tag files in BMA'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_bma_moderator',
            field=models.BooleanField(default=False, help_text='User can approve/unapprove files in BMA'),
        ),
    ]
