# Generated by Django 5.0.3 on 2024-04-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_bma_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text='The description field of the user profile on the BornHack website.'),
        ),
    ]
