# Generated by Django 5.0.3 on 2024-05-06 17:44

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pictures', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='The tags for this picture', through='utils.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
