# Generated by Django 5.0.3 on 2024-04-05 19:38

import files.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_basefile_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basefile",
            options={
                "ordering": ["created"],
                "permissions": (
                    ("unapprove_basefile", "Unapprove file"),
                    ("approve_basefile", "Approve file"),
                    ("unpublish_basefile", "Unpublish file"),
                    ("publish_basefile", "Publish file"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="basefile",
            name="file_size",
            field=models.PositiveIntegerField(
                help_text="The size of the file in bytes. This value is read-only."
            ),
        ),
        migrations.AlterField(
            model_name="basefile",
            name="license",
            field=models.CharField(
                choices=[
                    ("CC_ZERO_1_0", "Creative Commons CC0 1.0 Universal"),
                    ("CC_BY_4_0", "Creative Commons Attribution 4.0 International"),
                    (
                        "CC_BY_SA_4_0",
                        "Creative Commons Attribution-ShareAlike 4.0 International",
                    ),
                ],
                help_text="The license for this file. The license can not be changed after the file is uploaded.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="basefile",
            name="original_filename",
            field=models.CharField(
                help_text="The original (uploaded) filename. This value is read-only.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="basefile",
            name="thumbnail_url",
            field=models.CharField(
                help_text="Relative URL to the image to use as thumbnail for this file. This must be a string beginning with /static/images/ or /media/",
                max_length=255,
                validators=[files.validators.validate_thumbnail_url],
            ),
        ),
    ]
