# Generated by Django 5.0.3 on 2024-04-14 06:06

import files.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_basefile_options_alter_basefile_file_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basefile',
            options={'ordering': ('created',), 'permissions': (('unapprove_basefile', 'Unapprove file'), ('approve_basefile', 'Approve file'), ('unpublish_basefile', 'Unpublish file'), ('publish_basefile', 'Publish file'))},
        ),
        migrations.AlterField(
            model_name='basefile',
            name='status',
            field=models.CharField(choices=[('PENDING_MODERATION', 'Pending Moderation'), ('UNPUBLISHED', 'Unpublished'), ('PUBLISHED', 'Published'), ('PENDING_DELETION', 'Pending Deletion')], default='PENDING_MODERATION', help_text='The status of this file. Only published files are visible on the public website.', max_length=20, validators=[files.validators.validate_file_status]),
        ),
    ]
