# Generated by Django 5.0.3 on 2024-04-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_basefile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basefile',
            old_name='source',
            new_name='original_source',
        ),
    ]
