# Generated by Django 5.0.3 on 2024-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_rename_source_basefile_original_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basefile',
            old_name='owner',
            new_name='uploader',
        ),
    ]
