# Generated by Django 5.0.3 on 2024-05-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_initial'),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='invisible',
        ),
        migrations.AddField(
            model_name='album',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Set true to mark album as deleted.'),
        ),
        migrations.AlterField(
            model_name='albummember',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='albummember',
            name='basefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='files.basefile'),
        ),
    ]
